--[[
	Auto-generated GUI Script V2.1
	Created by: Omniverse Highland Studio
	Plugin: GUI to Proper Script Converter V2.1

	⚡ ULTIMATE ACCURACY - FIXED:
	- 100% Property Detection
	- Full FontFace Support
	- Perfect LayoutOrder
	- Responsive Design (AutomaticSize)
	- Zero Missed Properties
	- Custom Variable Names (OVHL_UI_)
]]

local Players = game:GetService("Players")
local player = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")

local OVHL_UI_1 = Instance.new("ScreenGui")
OVHL_UI_1.ClipToDeviceSafeArea = true
OVHL_UI_1.DisplayOrder = 10
OVHL_UI_1.Enabled = true
OVHL_UI_1.IgnoreGuiInset = true
OVHL_UI_1.SafeAreaCompatibility = Enum.SafeAreaCompatibility.FullscreenExtension
OVHL_UI_1.ScreenInsets = Enum.ScreenInsets.DeviceSafeInsets
OVHL_UI_1.ZIndexBehavior = Enum.ZIndexBehavior.Global
OVHL_UI_1.Name = "MusicPlayerGUI"
local OVHL_UI_2 = Instance.new("Frame")
OVHL_UI_2.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_2.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_2.BackgroundTransparency = 1
OVHL_UI_2.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_2.BorderMode = Enum.BorderMode.Outline
OVHL_UI_2.BorderSizePixel = 0
OVHL_UI_2.Position = UDim2.new(0.075, 0, 0.02, 0)
OVHL_UI_2.Size = UDim2.new(0.85, 0, 0.86, 0)
OVHL_UI_2.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_2.Style = Enum.FrameStyle.Custom
OVHL_UI_2.Name = "PaddingFrame"
local OVHL_UI_3 = Instance.new("Frame")
OVHL_UI_3.AnchorPoint = Vector2.new(0.5, 0)
OVHL_UI_3.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_3.BackgroundColor3 = Color3.fromRGB(85, 0, 0)
OVHL_UI_3.BackgroundTransparency = 1
OVHL_UI_3.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_3.BorderMode = Enum.BorderMode.Outline
OVHL_UI_3.BorderSizePixel = 0
OVHL_UI_3.Position = UDim2.new(0.5, 0, 0, 0)
OVHL_UI_3.Size = UDim2.new(0.4, 0, 1, 0)
OVHL_UI_3.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_3.Style = Enum.FrameStyle.Custom
OVHL_UI_3.Name = "MainContainer"
local OVHL_UI_4 = Instance.new("ImageLabel")
OVHL_UI_4.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_4.BackgroundTransparency = 1
OVHL_UI_4.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_4.BorderMode = Enum.BorderMode.Outline
OVHL_UI_4.BorderSizePixel = 0
OVHL_UI_4.Image = "rbxassetid://136464578605531"
OVHL_UI_4.ImageColor3 = Color3.fromRGB(255, 255, 255)
OVHL_UI_4.ImageRectOffset = Vector2.new(0, 0)
OVHL_UI_4.ImageRectSize = Vector2.new(0, 0)
OVHL_UI_4.ImageTransparency = 0.07000000029802322
OVHL_UI_4.ResampleMode = Enum.ResamplerMode.Default
OVHL_UI_4.ScaleType = Enum.ScaleType.Crop
OVHL_UI_4.Size = UDim2.new(1, 0, 1, 0)
OVHL_UI_4.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_4.SliceCenter = Rect.new(0, 0, 0, 0)
OVHL_UI_4.SliceScale = 1
OVHL_UI_4.TileSize = UDim2.new(1, 0, 1, 0)
OVHL_UI_4.Name = "BackgroundImage"
local OVHL_UI_5 = Instance.new("UICorner")
OVHL_UI_5.CornerRadius = UDim.new(0, 20)
OVHL_UI_5.Name = "BackgroundCorner"
OVHL_UI_5.Parent = OVHL_UI_4

local OVHL_UI_6 = Instance.new("UIStroke")
OVHL_UI_6.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
OVHL_UI_6.Color = Color3.fromRGB(255, 255, 255)
OVHL_UI_6.LineJoinMode = Enum.LineJoinMode.Round
OVHL_UI_6.Thickness = 2
OVHL_UI_6.Transparency = 0.30000001192092896
OVHL_UI_6.Name = "BackgroundStroke"
OVHL_UI_6.Parent = OVHL_UI_4

OVHL_UI_4.Parent = OVHL_UI_3

local OVHL_UI_7 = Instance.new("Frame")
OVHL_UI_7.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_7.BackgroundTransparency = 1
OVHL_UI_7.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_7.BorderMode = Enum.BorderMode.Outline
OVHL_UI_7.BorderSizePixel = 0
OVHL_UI_7.Size = UDim2.new(1, 0, 1, 0)
OVHL_UI_7.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_7.Style = Enum.FrameStyle.Custom
OVHL_UI_7.Name = "ContentFrame"
local OVHL_UI_8 = Instance.new("UIListLayout")
OVHL_UI_8.HorizontalAlignment = Enum.HorizontalAlignment.Center
OVHL_UI_8.HorizontalFlex = Enum.UIFlexAlignment.SpaceAround
OVHL_UI_8.ItemLineAlignment = Enum.ItemLineAlignment.Center
OVHL_UI_8.Padding = UDim.new(0.02, 0)
OVHL_UI_8.SortOrder = Enum.SortOrder.LayoutOrder
OVHL_UI_8.Name = "UIListLayout"
OVHL_UI_8.Parent = OVHL_UI_7

local OVHL_UI_9 = Instance.new("UIPadding")
OVHL_UI_9.PaddingBottom = UDim.new(0, 15)
OVHL_UI_9.PaddingLeft = UDim.new(0, 15)
OVHL_UI_9.PaddingRight = UDim.new(0, 15)
OVHL_UI_9.PaddingTop = UDim.new(0, 15)
OVHL_UI_9.Name = "UIPadding"
OVHL_UI_9.Parent = OVHL_UI_7

local OVHL_UI_10 = Instance.new("Frame")
OVHL_UI_10.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_10.BackgroundTransparency = 1
OVHL_UI_10.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_10.BorderMode = Enum.BorderMode.Outline
OVHL_UI_10.BorderSizePixel = 0
OVHL_UI_10.LayoutOrder = 1
OVHL_UI_10.Size = UDim2.new(1, 0, 0.0495651, 0)
OVHL_UI_10.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_10.Style = Enum.FrameStyle.Custom
OVHL_UI_10.Name = "HeaderFrame"
local OVHL_UI_11 = Instance.new("UIListLayout")
OVHL_UI_11.FillDirection = Enum.FillDirection.Horizontal
OVHL_UI_11.HorizontalAlignment = Enum.HorizontalAlignment.Center
OVHL_UI_11.HorizontalFlex = Enum.UIFlexAlignment.SpaceBetween
OVHL_UI_11.SortOrder = Enum.SortOrder.LayoutOrder
OVHL_UI_11.VerticalAlignment = Enum.VerticalAlignment.Center
OVHL_UI_11.Wraps = true
OVHL_UI_11.Name = "UIListLayout"
OVHL_UI_11.Parent = OVHL_UI_10

local OVHL_UI_12 = Instance.new("TextButton")
OVHL_UI_12.Active = true
OVHL_UI_12.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_12.BackgroundTransparency = 1
OVHL_UI_12.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_12.BorderMode = Enum.BorderMode.Outline
OVHL_UI_12.BorderSizePixel = 0
OVHL_UI_12.FontFace =
    Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
OVHL_UI_12.LayoutOrder = 1
OVHL_UI_12.LineHeight = 1
OVHL_UI_12.MaxVisibleGraphemes = -1
OVHL_UI_12.Position = UDim2.new(0, 0, 0.1, 0)
OVHL_UI_12.Size = UDim2.new(0.090608, 0, 1, 0)
OVHL_UI_12.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_12.Text = "≡"
OVHL_UI_12.TextColor3 = Color3.fromRGB(255, 255, 255)
OVHL_UI_12.TextDirection = Enum.TextDirection.Auto
OVHL_UI_12.TextScaled = true
OVHL_UI_12.TextSize = 20
OVHL_UI_12.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_12.TextTruncate = Enum.TextTruncate.None
OVHL_UI_12.TextWrapped = true
OVHL_UI_12.Name = "MenuButton"
OVHL_UI_12.Parent = OVHL_UI_10

local OVHL_UI_13 = Instance.new("TextLabel")
OVHL_UI_13.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_13.BackgroundTransparency = 1
OVHL_UI_13.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_13.BorderMode = Enum.BorderMode.Outline
OVHL_UI_13.BorderSizePixel = 0
OVHL_UI_13.FontFace = Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
OVHL_UI_13.LayoutOrder = 2
OVHL_UI_13.LineHeight = 1
OVHL_UI_13.MaxVisibleGraphemes = -1
OVHL_UI_13.Position = UDim2.new(0.0906082, 0, 0, 0)
OVHL_UI_13.Size = UDim2.new(0.674423, 0, 1, 0)
OVHL_UI_13.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_13.Text = "MUSIC PLAYER"
OVHL_UI_13.TextColor3 = Color3.fromRGB(255, 255, 255)
OVHL_UI_13.TextDirection = Enum.TextDirection.Auto
OVHL_UI_13.TextScaled = true
OVHL_UI_13.TextSize = 20
OVHL_UI_13.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_13.TextTruncate = Enum.TextTruncate.None
OVHL_UI_13.TextWrapped = true
OVHL_UI_13.Name = "TextLabel"
OVHL_UI_13.Parent = OVHL_UI_10

local OVHL_UI_14 = Instance.new("TextButton")
OVHL_UI_14.Active = true
OVHL_UI_14.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_14.BackgroundTransparency = 1
OVHL_UI_14.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_14.BorderMode = Enum.BorderMode.Outline
OVHL_UI_14.BorderSizePixel = 0
OVHL_UI_14.FontFace = Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
OVHL_UI_14.LayoutOrder = 3
OVHL_UI_14.LineHeight = 1
OVHL_UI_14.MaxVisibleGraphemes = -1
OVHL_UI_14.Position = UDim2.new(0.909896, 0, 0.05, 0)
OVHL_UI_14.Size = UDim2.new(0.0901042, 0, 0.9, 0)
OVHL_UI_14.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_14.Text = "X"
OVHL_UI_14.TextColor3 = Color3.fromRGB(255, 255, 255)
OVHL_UI_14.TextDirection = Enum.TextDirection.Auto
OVHL_UI_14.TextScaled = true
OVHL_UI_14.TextSize = 25
OVHL_UI_14.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_14.TextTruncate = Enum.TextTruncate.None
OVHL_UI_14.TextWrapped = true
OVHL_UI_14.Name = "CloseButton"
OVHL_UI_14.Parent = OVHL_UI_10

OVHL_UI_10.Parent = OVHL_UI_7

local OVHL_UI_15 = Instance.new("Frame")
OVHL_UI_15.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_15.BackgroundTransparency = 0.6000000238418579
OVHL_UI_15.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_15.BorderMode = Enum.BorderMode.Outline
OVHL_UI_15.BorderSizePixel = 0
OVHL_UI_15.LayoutOrder = 2
OVHL_UI_15.Position = UDim2.new(0.000724, 0, 0.08, 0)
OVHL_UI_15.Size = UDim2.new(1, 0, 0.4, 0)
OVHL_UI_15.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_15.Style = Enum.FrameStyle.Custom
OVHL_UI_15.Name = "NowPlayingBox"
local OVHL_UI_16 = Instance.new("UICorner")
OVHL_UI_16.CornerRadius = UDim.new(0, 20)
OVHL_UI_16.Name = "BackgroundCorner"
OVHL_UI_16.Parent = OVHL_UI_15

local OVHL_UI_17 = Instance.new("UIListLayout")
OVHL_UI_17.HorizontalAlignment = Enum.HorizontalAlignment.Center
OVHL_UI_17.ItemLineAlignment = Enum.ItemLineAlignment.Center
OVHL_UI_17.Padding = UDim.new(0, 3)
OVHL_UI_17.SortOrder = Enum.SortOrder.LayoutOrder
OVHL_UI_17.VerticalAlignment = Enum.VerticalAlignment.Center
OVHL_UI_17.VerticalFlex = Enum.UIFlexAlignment.SpaceEvenly
OVHL_UI_17.Name = "UIListLayout"
OVHL_UI_17.Parent = OVHL_UI_15

local OVHL_UI_18 = Instance.new("UIPadding")
OVHL_UI_18.PaddingBottom = UDim.new(0, 10)
OVHL_UI_18.PaddingLeft = UDim.new(0, 10)
OVHL_UI_18.PaddingRight = UDim.new(0, 10)
OVHL_UI_18.PaddingTop = UDim.new(0, 10)
OVHL_UI_18.Name = "UIPadding"
OVHL_UI_18.Parent = OVHL_UI_15

local OVHL_UI_19 = Instance.new("Frame")
OVHL_UI_19.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_19.BackgroundTransparency = 1
OVHL_UI_19.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_19.BorderMode = Enum.BorderMode.Outline
OVHL_UI_19.BorderSizePixel = 0
OVHL_UI_19.Size = UDim2.new(0.8, 0, 0.8, 0)
OVHL_UI_19.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_19.Style = Enum.FrameStyle.Custom
OVHL_UI_19.Name = "VinylFrame"
local OVHL_UI_20 = Instance.new("UIAspectRatioConstraint")
OVHL_UI_20.AspectRatio = 1
OVHL_UI_20.AspectType = Enum.AspectType.FitWithinMaxSize
OVHL_UI_20.DominantAxis = Enum.DominantAxis.Width
OVHL_UI_20.Name = "UIAspectRatioConstraint"
OVHL_UI_20.Parent = OVHL_UI_19

local OVHL_UI_21 = Instance.new("UICorner")
OVHL_UI_21.CornerRadius = UDim.new(1, 0)
OVHL_UI_21.Name = "UICorner"
OVHL_UI_21.Parent = OVHL_UI_19

local OVHL_UI_22 = Instance.new("ImageLabel")
OVHL_UI_22.AnchorPoint = Vector2.new(0.5, 0.5)
OVHL_UI_22.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_22.BackgroundTransparency = 1
OVHL_UI_22.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_22.BorderMode = Enum.BorderMode.Outline
OVHL_UI_22.BorderSizePixel = 0
OVHL_UI_22.Image = "rbxassetid://86002587869819"
OVHL_UI_22.ImageColor3 = Color3.fromRGB(255, 255, 255)
OVHL_UI_22.ImageRectOffset = Vector2.new(0, 0)
OVHL_UI_22.ImageRectSize = Vector2.new(0, 0)
OVHL_UI_22.LayoutOrder = 1
OVHL_UI_22.Position = UDim2.new(0.5, 0, 0.5, 0)
OVHL_UI_22.ResampleMode = Enum.ResamplerMode.Default
OVHL_UI_22.Rotation = -180
OVHL_UI_22.Size = UDim2.new(1, 0, 1, 0)
OVHL_UI_22.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_22.SliceCenter = Rect.new(0, 0, 0, 0)
OVHL_UI_22.SliceScale = 1
OVHL_UI_22.TileSize = UDim2.new(1, 0, 1, 0)
OVHL_UI_22.Name = "VinylArt"
local OVHL_UI_23 = Instance.new("UIAspectRatioConstraint")
OVHL_UI_23.AspectRatio = 1
OVHL_UI_23.AspectType = Enum.AspectType.FitWithinMaxSize
OVHL_UI_23.DominantAxis = Enum.DominantAxis.Width
OVHL_UI_23.Name = "UIAspectRatioConstraint"
OVHL_UI_23.Parent = OVHL_UI_22

OVHL_UI_22.Parent = OVHL_UI_19

OVHL_UI_19.Parent = OVHL_UI_15

local OVHL_UI_24 = Instance.new("TextLabel")
OVHL_UI_24.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_24.BackgroundTransparency = 1
OVHL_UI_24.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_24.BorderMode = Enum.BorderMode.Outline
OVHL_UI_24.BorderSizePixel = 0
OVHL_UI_24.FontFace = Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
OVHL_UI_24.LayoutOrder = 2
OVHL_UI_24.LineHeight = 1
OVHL_UI_24.MaxVisibleGraphemes = -1
OVHL_UI_24.Size = UDim2.new(0.8, 0, 0.12, 0)
OVHL_UI_24.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_24.Text = "JUDUL LAGU"
OVHL_UI_24.TextColor3 = Color3.fromRGB(255, 255, 255)
OVHL_UI_24.TextDirection = Enum.TextDirection.Auto
OVHL_UI_24.TextScaled = true
OVHL_UI_24.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_24.TextTruncate = Enum.TextTruncate.None
OVHL_UI_24.TextWrapped = true
OVHL_UI_24.Name = "JudulLagu"
OVHL_UI_24.Parent = OVHL_UI_15

local OVHL_UI_25 = Instance.new("Frame")
OVHL_UI_25.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_25.BackgroundTransparency = 1
OVHL_UI_25.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_25.BorderMode = Enum.BorderMode.Outline
OVHL_UI_25.BorderSizePixel = 0
OVHL_UI_25.LayoutOrder = 3
OVHL_UI_25.Size = UDim2.new(0.8, 0, 0.08, 0)
OVHL_UI_25.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_25.Style = Enum.FrameStyle.Custom
OVHL_UI_25.Name = "ArtistGenreFrame"
local OVHL_UI_26 = Instance.new("UIListLayout")
OVHL_UI_26.FillDirection = Enum.FillDirection.Horizontal
OVHL_UI_26.HorizontalAlignment = Enum.HorizontalAlignment.Center
OVHL_UI_26.Padding = UDim.new(0, 10)
OVHL_UI_26.SortOrder = Enum.SortOrder.LayoutOrder
OVHL_UI_26.VerticalAlignment = Enum.VerticalAlignment.Center
OVHL_UI_26.VerticalFlex = Enum.UIFlexAlignment.SpaceEvenly
OVHL_UI_26.Name = "UIListLayout"
OVHL_UI_26.Parent = OVHL_UI_25

local OVHL_UI_27 = Instance.new("TextLabel")
OVHL_UI_27.AutomaticSize = Enum.AutomaticSize.X
OVHL_UI_27.BackgroundTransparency = 1
OVHL_UI_27.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_27.BorderMode = Enum.BorderMode.Outline
OVHL_UI_27.BorderSizePixel = 0
OVHL_UI_27.FontFace = Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
OVHL_UI_27.LayoutOrder = 1
OVHL_UI_27.LineHeight = 1
OVHL_UI_27.MaxVisibleGraphemes = -1
OVHL_UI_27.Size = UDim2.new(1, 0, 1, 0)
OVHL_UI_27.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_27.Text = "Artis - Genre"
OVHL_UI_27.TextColor3 = Color3.fromRGB(255, 255, 255)
OVHL_UI_27.TextDirection = Enum.TextDirection.Auto
OVHL_UI_27.TextScaled = true
OVHL_UI_27.TextSize = 12
OVHL_UI_27.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_27.TextTruncate = Enum.TextTruncate.None
OVHL_UI_27.TextWrapped = true
OVHL_UI_27.Name = "ArtistGenreText"
OVHL_UI_27.Parent = OVHL_UI_25

OVHL_UI_25.Parent = OVHL_UI_15

OVHL_UI_15.Parent = OVHL_UI_7

local OVHL_UI_28 = Instance.new("Frame")
OVHL_UI_28.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_28.BackgroundTransparency = 1
OVHL_UI_28.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_28.BorderMode = Enum.BorderMode.Outline
OVHL_UI_28.BorderSizePixel = 0
OVHL_UI_28.LayoutOrder = 3
OVHL_UI_28.Size = UDim2.new(1, 0, 0.25, 0)
OVHL_UI_28.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_28.Style = Enum.FrameStyle.Custom
OVHL_UI_28.Name = "PlaylistFrame"
local OVHL_UI_29 = Instance.new("ScrollingFrame")
OVHL_UI_29.Active = true
OVHL_UI_29.AutomaticCanvasSize = Enum.AutomaticSize.Y
OVHL_UI_29.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_29.BackgroundTransparency = 1
OVHL_UI_29.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_29.BorderMode = Enum.BorderMode.Outline
OVHL_UI_29.BorderSizePixel = 0
OVHL_UI_29.BottomImage = "rbxasset://textures/ui/Scroll/scroll-bottom.png"
OVHL_UI_29.CanvasSize = UDim2.new(0, 0, 0, 300)
OVHL_UI_29.ClipsDescendants = true
OVHL_UI_29.HorizontalScrollBarInset = Enum.ScrollBarInset.None
OVHL_UI_29.MidImage = "rbxasset://textures/ui/Scroll/scroll-middle.png"
OVHL_UI_29.ScrollBarImageColor3 = Color3.fromRGB(255, 255, 255)
OVHL_UI_29.ScrollBarThickness = 3
OVHL_UI_29.ScrollingDirection = Enum.ScrollingDirection.XY
OVHL_UI_29.Size = UDim2.new(1, 0, 1, 0)
OVHL_UI_29.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_29.TopImage = "rbxasset://textures/ui/Scroll/scroll-top.png"
OVHL_UI_29.VerticalScrollBarInset = Enum.ScrollBarInset.None
OVHL_UI_29.VerticalScrollBarPosition = Enum.VerticalScrollBarPosition.Right
OVHL_UI_29.Name = "PlaylistScroll"
local OVHL_UI_30 = Instance.new("Frame")
OVHL_UI_30.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_30.BackgroundTransparency = 0.5
OVHL_UI_30.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_30.BorderMode = Enum.BorderMode.Outline
OVHL_UI_30.BorderSizePixel = 0
OVHL_UI_30.Size = UDim2.new(1, 0, 0.2, 0)
OVHL_UI_30.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_30.Style = Enum.FrameStyle.Custom
OVHL_UI_30.Name = "PlaylistItemTemplate"
local OVHL_UI_31 = Instance.new("UICorner")
OVHL_UI_31.CornerRadius = UDim.new(0, 10)
OVHL_UI_31.Name = "UICorner"
OVHL_UI_31.Parent = OVHL_UI_30

local OVHL_UI_32 = Instance.new("UIListLayout")
OVHL_UI_32.FillDirection = Enum.FillDirection.Horizontal
OVHL_UI_32.HorizontalAlignment = Enum.HorizontalAlignment.Center
OVHL_UI_32.HorizontalFlex = Enum.UIFlexAlignment.SpaceBetween
OVHL_UI_32.SortOrder = Enum.SortOrder.LayoutOrder
OVHL_UI_32.VerticalAlignment = Enum.VerticalAlignment.Center
OVHL_UI_32.Name = "UIListLayout"
OVHL_UI_32.Parent = OVHL_UI_30

local OVHL_UI_33 = Instance.new("UIPadding")
OVHL_UI_33.PaddingLeft = UDim.new(0, 10)
OVHL_UI_33.PaddingRight = UDim.new(0, 10)
OVHL_UI_33.Name = "UIPadding"
OVHL_UI_33.Parent = OVHL_UI_30

local OVHL_UI_34 = Instance.new("ImageButton")
OVHL_UI_34.Active = true
OVHL_UI_34.AutoButtonColor = false
OVHL_UI_34.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_34.BackgroundColor3 = Color3.fromRGB(163, 162, 165)
OVHL_UI_34.BackgroundTransparency = 1
OVHL_UI_34.BorderMode = Enum.BorderMode.Outline
OVHL_UI_34.HoverImage = ""
OVHL_UI_34.Image = "rbxassetid://89914489526642"
OVHL_UI_34.ImageColor3 = Color3.fromRGB(255, 255, 255)
OVHL_UI_34.ImageRectOffset = Vector2.new(0, 0)
OVHL_UI_34.ImageRectSize = Vector2.new(0, 0)
OVHL_UI_34.LayoutOrder = 1
OVHL_UI_34.PressedImage = ""
OVHL_UI_34.ResampleMode = Enum.ResamplerMode.Default
OVHL_UI_34.ScaleType = Enum.ScaleType.Fit
OVHL_UI_34.Size = UDim2.new(0.1, 0, 0.7, 0)
OVHL_UI_34.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_34.SliceCenter = Rect.new(0, 0, 0, 0)
OVHL_UI_34.SliceScale = 1
OVHL_UI_34.TileSize = UDim2.new(1, 0, 1, 0)
OVHL_UI_34.Name = "PlayIcon"
OVHL_UI_34.Parent = OVHL_UI_30

local OVHL_UI_35 = Instance.new("TextLabel")
OVHL_UI_35.AutomaticSize = Enum.AutomaticSize.Y
OVHL_UI_35.BackgroundTransparency = 1
OVHL_UI_35.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_35.BorderMode = Enum.BorderMode.Outline
OVHL_UI_35.BorderSizePixel = 0
OVHL_UI_35.FontFace =
    Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.SemiBold, Enum.FontStyle.Normal)
OVHL_UI_35.LayoutOrder = 2
OVHL_UI_35.LineHeight = 1
OVHL_UI_35.MaxVisibleGraphemes = -1
OVHL_UI_35.Size = UDim2.new(0.75, 0, 0.7, 0)
OVHL_UI_35.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_35.Text = "Judul - Artis - Genre"
OVHL_UI_35.TextColor3 = Color3.fromRGB(255, 255, 255)
OVHL_UI_35.TextDirection = Enum.TextDirection.Auto
OVHL_UI_35.TextScaled = true
OVHL_UI_35.TextSize = 16
OVHL_UI_35.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_35.TextTruncate = Enum.TextTruncate.AtEnd
OVHL_UI_35.TextWrapped = true
OVHL_UI_35.TextXAlignment = Enum.TextXAlignment.Left
OVHL_UI_35.Name = "SongInfo"
OVHL_UI_35.Parent = OVHL_UI_30

local OVHL_UI_36 = Instance.new("ImageButton")
OVHL_UI_36.Active = true
OVHL_UI_36.AutoButtonColor = false
OVHL_UI_36.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_36.BackgroundColor3 = Color3.fromRGB(163, 162, 165)
OVHL_UI_36.BackgroundTransparency = 1
OVHL_UI_36.BorderMode = Enum.BorderMode.Outline
OVHL_UI_36.HoverImage = ""
OVHL_UI_36.Image = "rbxassetid://130010482065235"
OVHL_UI_36.ImageColor3 = Color3.fromRGB(255, 255, 255)
OVHL_UI_36.ImageRectOffset = Vector2.new(0, 0)
OVHL_UI_36.ImageRectSize = Vector2.new(0, 0)
OVHL_UI_36.LayoutOrder = 3
OVHL_UI_36.PressedImage = ""
OVHL_UI_36.ResampleMode = Enum.ResamplerMode.Default
OVHL_UI_36.ScaleType = Enum.ScaleType.Fit
OVHL_UI_36.Size = UDim2.new(0.1, 0, 0.4, 0)
OVHL_UI_36.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_36.SliceCenter = Rect.new(0, 0, 0, 0)
OVHL_UI_36.SliceScale = 1
OVHL_UI_36.TileSize = UDim2.new(1, 0, 1, 0)
OVHL_UI_36.Name = "MenuIcon"
OVHL_UI_36.Parent = OVHL_UI_30

OVHL_UI_30.Parent = OVHL_UI_29

local OVHL_UI_37 = Instance.new("UIListLayout")
OVHL_UI_37.HorizontalAlignment = Enum.HorizontalAlignment.Center
OVHL_UI_37.HorizontalFlex = Enum.UIFlexAlignment.Fill
OVHL_UI_37.Padding = UDim.new(0, 5)
OVHL_UI_37.SortOrder = Enum.SortOrder.LayoutOrder
OVHL_UI_37.Name = "UIListLayout"
OVHL_UI_37.Parent = OVHL_UI_29

local OVHL_UI_38 = Instance.new("UIPadding")
OVHL_UI_38.PaddingLeft = UDim.new(0, 5)
OVHL_UI_38.PaddingRight = UDim.new(0, 5)
OVHL_UI_38.Name = "UIPadding"
OVHL_UI_38.Parent = OVHL_UI_29

OVHL_UI_29.Parent = OVHL_UI_28

OVHL_UI_28.Parent = OVHL_UI_7

local OVHL_UI_39 = Instance.new("Frame")
OVHL_UI_39.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_39.BackgroundTransparency = 1
OVHL_UI_39.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_39.BorderMode = Enum.BorderMode.Outline
OVHL_UI_39.BorderSizePixel = 0
OVHL_UI_39.LayoutOrder = 4
OVHL_UI_39.Position = UDim2.new(0, 0, 0.809565, 0)
OVHL_UI_39.Size = UDim2.new(1, 0, 0.2, 0)
OVHL_UI_39.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_39.Style = Enum.FrameStyle.Custom
OVHL_UI_39.Name = "MediaButtonFrame"
local OVHL_UI_40 = Instance.new("UIListLayout")
OVHL_UI_40.HorizontalAlignment = Enum.HorizontalAlignment.Center
OVHL_UI_40.SortOrder = Enum.SortOrder.LayoutOrder
OVHL_UI_40.VerticalAlignment = Enum.VerticalAlignment.Center
OVHL_UI_40.VerticalFlex = Enum.UIFlexAlignment.SpaceAround
OVHL_UI_40.Name = "UIListLayout"
OVHL_UI_40.Parent = OVHL_UI_39

local OVHL_UI_41 = Instance.new("Frame")
OVHL_UI_41.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_41.BackgroundColor3 = Color3.fromRGB(0, 255, 255)
OVHL_UI_41.BackgroundTransparency = 1
OVHL_UI_41.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_41.BorderMode = Enum.BorderMode.Outline
OVHL_UI_41.BorderSizePixel = 0
OVHL_UI_41.LayoutOrder = 1
OVHL_UI_41.Position = UDim2.new(0.225, 0, 0, 0)
OVHL_UI_41.Size = UDim2.new(0.55, 0, 0.557156, 0)
OVHL_UI_41.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_41.Style = Enum.FrameStyle.Custom
OVHL_UI_41.Name = "ControlGroup"
local OVHL_UI_42 = Instance.new("UIListLayout")
OVHL_UI_42.FillDirection = Enum.FillDirection.Horizontal
OVHL_UI_42.HorizontalAlignment = Enum.HorizontalAlignment.Center
OVHL_UI_42.HorizontalFlex = Enum.UIFlexAlignment.SpaceEvenly
OVHL_UI_42.SortOrder = Enum.SortOrder.LayoutOrder
OVHL_UI_42.VerticalAlignment = Enum.VerticalAlignment.Center
OVHL_UI_42.Name = "UIListLayout"
OVHL_UI_42.Parent = OVHL_UI_41

local OVHL_UI_43 = Instance.new("ImageButton")
OVHL_UI_43.Active = true
OVHL_UI_43.AutoButtonColor = false
OVHL_UI_43.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_43.BackgroundColor3 = Color3.fromRGB(163, 162, 165)
OVHL_UI_43.BackgroundTransparency = 1
OVHL_UI_43.BorderMode = Enum.BorderMode.Outline
OVHL_UI_43.HoverImage = ""
OVHL_UI_43.Image = "rbxassetid://129306585952986"
OVHL_UI_43.ImageColor3 = Color3.fromRGB(255, 255, 255)
OVHL_UI_43.ImageRectOffset = Vector2.new(0, 0)
OVHL_UI_43.ImageRectSize = Vector2.new(0, 0)
OVHL_UI_43.LayoutOrder = 1
OVHL_UI_43.PressedImage = ""
OVHL_UI_43.ResampleMode = Enum.ResamplerMode.Default
OVHL_UI_43.ScaleType = Enum.ScaleType.Fit
OVHL_UI_43.Size = UDim2.new(0.2, 0, 0.6, 0)
OVHL_UI_43.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_43.SliceCenter = Rect.new(0, 0, 0, 0)
OVHL_UI_43.SliceScale = 1
OVHL_UI_43.TileSize = UDim2.new(1, 0, 1, 0)
OVHL_UI_43.Name = "PreviousButton"
OVHL_UI_43.Parent = OVHL_UI_41

local OVHL_UI_44 = Instance.new("ImageButton")
OVHL_UI_44.Active = true
OVHL_UI_44.AutoButtonColor = false
OVHL_UI_44.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_44.BackgroundColor3 = Color3.fromRGB(163, 162, 165)
OVHL_UI_44.BackgroundTransparency = 1
OVHL_UI_44.BorderMode = Enum.BorderMode.Outline
OVHL_UI_44.HoverImage = ""
OVHL_UI_44.Image = "rbxassetid://89914489526642"
OVHL_UI_44.ImageColor3 = Color3.fromRGB(255, 255, 255)
OVHL_UI_44.ImageRectOffset = Vector2.new(0, 0)
OVHL_UI_44.ImageRectSize = Vector2.new(0, 0)
OVHL_UI_44.LayoutOrder = 2
OVHL_UI_44.PressedImage = ""
OVHL_UI_44.ResampleMode = Enum.ResamplerMode.Default
OVHL_UI_44.ScaleType = Enum.ScaleType.Fit
OVHL_UI_44.Size = UDim2.new(0.4, 0, 0.9, 0)
OVHL_UI_44.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_44.SliceCenter = Rect.new(0, 0, 0, 0)
OVHL_UI_44.SliceScale = 1
OVHL_UI_44.TileSize = UDim2.new(1, 0, 1, 0)
OVHL_UI_44.Name = "PlayButton"
OVHL_UI_44.Parent = OVHL_UI_41

local OVHL_UI_45 = Instance.new("ImageButton")
OVHL_UI_45.Active = true
OVHL_UI_45.AutoButtonColor = false
OVHL_UI_45.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_45.BackgroundColor3 = Color3.fromRGB(163, 162, 165)
OVHL_UI_45.BackgroundTransparency = 1
OVHL_UI_45.BorderMode = Enum.BorderMode.Outline
OVHL_UI_45.HoverImage = ""
OVHL_UI_45.Image = "rbxassetid://100389894024485"
OVHL_UI_45.ImageColor3 = Color3.fromRGB(255, 255, 255)
OVHL_UI_45.ImageRectOffset = Vector2.new(0, 0)
OVHL_UI_45.ImageRectSize = Vector2.new(0, 0)
OVHL_UI_45.LayoutOrder = 3
OVHL_UI_45.PressedImage = ""
OVHL_UI_45.ResampleMode = Enum.ResamplerMode.Default
OVHL_UI_45.ScaleType = Enum.ScaleType.Fit
OVHL_UI_45.Size = UDim2.new(0.2, 0, 0.6, 0)
OVHL_UI_45.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_45.SliceCenter = Rect.new(0, 0, 0, 0)
OVHL_UI_45.SliceScale = 1
OVHL_UI_45.TileSize = UDim2.new(1, 0, 1, 0)
OVHL_UI_45.Name = "NextButton"
OVHL_UI_45.Parent = OVHL_UI_41

OVHL_UI_41.Parent = OVHL_UI_39

local OVHL_UI_46 = Instance.new("Frame")
OVHL_UI_46.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_46.BackgroundTransparency = 1
OVHL_UI_46.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_46.BorderMode = Enum.BorderMode.Outline
OVHL_UI_46.BorderSizePixel = 0
OVHL_UI_46.LayoutOrder = 2
OVHL_UI_46.Position = UDim2.new(0, 0, 0.6, 0)
OVHL_UI_46.Size = UDim2.new(1, 0, 0.278578, 0)
OVHL_UI_46.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_46.Style = Enum.FrameStyle.Custom
OVHL_UI_46.Name = "BottomGroup"
local OVHL_UI_47 = Instance.new("UIListLayout")
OVHL_UI_47.FillDirection = Enum.FillDirection.Horizontal
OVHL_UI_47.HorizontalAlignment = Enum.HorizontalAlignment.Center
OVHL_UI_47.HorizontalFlex = Enum.UIFlexAlignment.SpaceAround
OVHL_UI_47.SortOrder = Enum.SortOrder.LayoutOrder
OVHL_UI_47.VerticalAlignment = Enum.VerticalAlignment.Center
OVHL_UI_47.Name = "UIListLayout"
OVHL_UI_47.Parent = OVHL_UI_46

local OVHL_UI_48 = Instance.new("Frame")
OVHL_UI_48.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_48.BackgroundTransparency = 1
OVHL_UI_48.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_48.BorderMode = Enum.BorderMode.Outline
OVHL_UI_48.BorderSizePixel = 0
OVHL_UI_48.Size = UDim2.new(0.5, 0, 0.8, 0)
OVHL_UI_48.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_48.Style = Enum.FrameStyle.Custom
OVHL_UI_48.Name = "VolumeGroup"
local OVHL_UI_49 = Instance.new("UIListLayout")
OVHL_UI_49.FillDirection = Enum.FillDirection.Horizontal
OVHL_UI_49.HorizontalAlignment = Enum.HorizontalAlignment.Center
OVHL_UI_49.HorizontalFlex = Enum.UIFlexAlignment.SpaceBetween
OVHL_UI_49.SortOrder = Enum.SortOrder.LayoutOrder
OVHL_UI_49.VerticalAlignment = Enum.VerticalAlignment.Center
OVHL_UI_49.Name = "UIListLayout"
OVHL_UI_49.Parent = OVHL_UI_48

local OVHL_UI_50 = Instance.new("ImageButton")
OVHL_UI_50.Active = true
OVHL_UI_50.AutoButtonColor = false
OVHL_UI_50.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_50.BackgroundColor3 = Color3.fromRGB(163, 162, 165)
OVHL_UI_50.BackgroundTransparency = 1
OVHL_UI_50.BorderMode = Enum.BorderMode.Outline
OVHL_UI_50.HoverImage = ""
OVHL_UI_50.Image = "rbxassetid://95086591790908"
OVHL_UI_50.ImageColor3 = Color3.fromRGB(255, 255, 255)
OVHL_UI_50.ImageRectOffset = Vector2.new(0, 0)
OVHL_UI_50.ImageRectSize = Vector2.new(0, 0)
OVHL_UI_50.LayoutOrder = 1
OVHL_UI_50.PressedImage = ""
OVHL_UI_50.ResampleMode = Enum.ResamplerMode.Default
OVHL_UI_50.ScaleType = Enum.ScaleType.Fit
OVHL_UI_50.Size = UDim2.new(0.2, 0, 0.8, 0)
OVHL_UI_50.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_50.SliceCenter = Rect.new(0, 0, 0, 0)
OVHL_UI_50.SliceScale = 1
OVHL_UI_50.TileSize = UDim2.new(1, 0, 1, 0)
OVHL_UI_50.Name = "VolumeDecreaseButton"
OVHL_UI_50.Parent = OVHL_UI_48

local OVHL_UI_51 = Instance.new("Frame")
OVHL_UI_51.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_51.BackgroundColor3 = Color3.fromRGB(191, 0, 96)
OVHL_UI_51.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_51.BorderMode = Enum.BorderMode.Outline
OVHL_UI_51.BorderSizePixel = 0
OVHL_UI_51.LayoutOrder = 2
OVHL_UI_51.Size = UDim2.new(0.5, 0, 0.3, 0)
OVHL_UI_51.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_51.Style = Enum.FrameStyle.Custom
OVHL_UI_51.Name = "VolumeSlider"
local OVHL_UI_52 = Instance.new("UICorner")
OVHL_UI_52.CornerRadius = UDim.new(0, 10)
OVHL_UI_52.Name = "UICorner"
OVHL_UI_52.Parent = OVHL_UI_51

local OVHL_UI_53 = Instance.new("Frame")
OVHL_UI_53.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_53.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_53.BorderMode = Enum.BorderMode.Outline
OVHL_UI_53.BorderSizePixel = 0
OVHL_UI_53.LayoutOrder = 2
OVHL_UI_53.Size = UDim2.new(0.7, 0, 1, 0)
OVHL_UI_53.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_53.Style = Enum.FrameStyle.Custom
OVHL_UI_53.Name = "VolumeProgress"
local OVHL_UI_54 = Instance.new("UICorner")
OVHL_UI_54.CornerRadius = UDim.new(0, 10)
OVHL_UI_54.Name = "UICorner"
OVHL_UI_54.Parent = OVHL_UI_53

OVHL_UI_53.Parent = OVHL_UI_51

OVHL_UI_51.Parent = OVHL_UI_48

local OVHL_UI_55 = Instance.new("ImageButton")
OVHL_UI_55.Active = true
OVHL_UI_55.AnchorPoint = Vector2.new(1, 0.5)
OVHL_UI_55.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_55.BackgroundTransparency = 1
OVHL_UI_55.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_55.BorderMode = Enum.BorderMode.Outline
OVHL_UI_55.BorderSizePixel = 0
OVHL_UI_55.HoverImage = ""
OVHL_UI_55.Image = "rbxassetid://116014539852278"
OVHL_UI_55.ImageColor3 = Color3.fromRGB(255, 255, 255)
OVHL_UI_55.ImageRectOffset = Vector2.new(0, 0)
OVHL_UI_55.ImageRectSize = Vector2.new(0, 0)
OVHL_UI_55.LayoutOrder = 3
OVHL_UI_55.PressedImage = ""
OVHL_UI_55.ResampleMode = Enum.ResamplerMode.Default
OVHL_UI_55.ScaleType = Enum.ScaleType.Fit
OVHL_UI_55.Size = UDim2.new(0.2, 0, 0.8, 0)
OVHL_UI_55.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_55.SliceCenter = Rect.new(0, 0, 0, 0)
OVHL_UI_55.SliceScale = 1
OVHL_UI_55.TileSize = UDim2.new(1, 0, 1, 0)
OVHL_UI_55.Name = "VolumeIncreaseButton"
OVHL_UI_55.Parent = OVHL_UI_48

OVHL_UI_48.Parent = OVHL_UI_46

local OVHL_UI_56 = Instance.new("TextButton")
OVHL_UI_56.Active = true
OVHL_UI_56.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_56.BackgroundColor3 = Color3.fromRGB(255, 0, 127)
OVHL_UI_56.BackgroundTransparency = 0.30000001192092896
OVHL_UI_56.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_56.BorderMode = Enum.BorderMode.Outline
OVHL_UI_56.BorderSizePixel = 0
OVHL_UI_56.FontFace = Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
OVHL_UI_56.LineHeight = 1
OVHL_UI_56.MaxVisibleGraphemes = -1
OVHL_UI_56.Position = UDim2.new(0.574472, 0, 0.1, 0)
OVHL_UI_56.Size = UDim2.new(0.375528, 0, 0.8, 0)
OVHL_UI_56.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_56.Text = "👍 VOTE TO SKIP"
OVHL_UI_56.TextColor3 = Color3.fromRGB(255, 255, 255)
OVHL_UI_56.TextDirection = Enum.TextDirection.Auto
OVHL_UI_56.TextScaled = true
OVHL_UI_56.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_56.TextTruncate = Enum.TextTruncate.None
OVHL_UI_56.TextWrapped = true
OVHL_UI_56.Name = "VoteSkipButton"
local OVHL_UI_57 = Instance.new("UICorner")
OVHL_UI_57.CornerRadius = UDim.new(0, 5)
OVHL_UI_57.Name = "UICorner"
OVHL_UI_57.Parent = OVHL_UI_56

local OVHL_UI_58 = Instance.new("UIPadding")
OVHL_UI_58.PaddingLeft = UDim.new(0, 10)
OVHL_UI_58.PaddingRight = UDim.new(0, 10)
OVHL_UI_58.Name = "UIPadding"
OVHL_UI_58.Parent = OVHL_UI_56

OVHL_UI_56.Parent = OVHL_UI_46

OVHL_UI_46.Parent = OVHL_UI_39

OVHL_UI_39.Parent = OVHL_UI_7

local OVHL_UI_59 = Instance.new("TextLabel")
OVHL_UI_59.AutomaticSize = Enum.AutomaticSize.None
OVHL_UI_59.BackgroundTransparency = 1
OVHL_UI_59.BorderColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_59.BorderMode = Enum.BorderMode.Outline
OVHL_UI_59.BorderSizePixel = 0
OVHL_UI_59.FontFace = Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic)
OVHL_UI_59.LayoutOrder = 5
OVHL_UI_59.LineHeight = 1
OVHL_UI_59.MaxVisibleGraphemes = -1
OVHL_UI_59.Size = UDim2.new(1, 0, 0, 20)
OVHL_UI_59.SizeConstraint = Enum.SizeConstraint.RelativeXY
OVHL_UI_59.Text = "© 2025 - Omniverse Highland Studio"
OVHL_UI_59.TextColor3 = Color3.fromRGB(255, 255, 255)
OVHL_UI_59.TextDirection = Enum.TextDirection.Auto
OVHL_UI_59.TextSize = 12
OVHL_UI_59.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
OVHL_UI_59.TextTruncate = Enum.TextTruncate.None
OVHL_UI_59.TextWrapped = true
OVHL_UI_59.Name = "FooterText"
OVHL_UI_59.Parent = OVHL_UI_7

OVHL_UI_7.Parent = OVHL_UI_3

local OVHL_UI_60 = Instance.new("UIAspectRatioConstraint")
OVHL_UI_60.AspectRatio = 0.5625
OVHL_UI_60.AspectType = Enum.AspectType.FitWithinMaxSize
OVHL_UI_60.DominantAxis = Enum.DominantAxis.Width
OVHL_UI_60.Name = "UIAspectRatioConstraint"
OVHL_UI_60.Parent = OVHL_UI_3

OVHL_UI_3.Parent = OVHL_UI_2

OVHL_UI_2.Parent = OVHL_UI_1

OVHL_UI_1.Parent = playerGui

return OVHL_UI_1
